import "bootstrap/dist/css/bootstrap.css";
import Head from "next/head";
import { createGlobalStyle } from "styled-components";
import Sidebar from "../Sidebar/Sidebar";
import Headers from "./Headers";

const GlobalStyle = createGlobalStyle`
html,
body{
  margin: 0;
  padding: 0;
  font-family: sans-serif;
}

ul, li{
  padding: 0;
  margin: 0;
  list-style-type: none;
}
a , a:hover {
  text-decoration: none;
}
.global {
  display: flex;
  .sidebar {
    width: 200px;
    height: 100vh;
    position: sticky;
    padding: 20px;
    top: 0;
    background-color: grey;
    .sidebar_link {
      display: flex;
      align-items: center;
      padding: 10px 20px;
      border-radius: 20px;
      transition: 0.5s;
      &:hover {
      background-color: yellowgreen;
      }
    }
  }
  .content{
    flex: 1;
  }
  .active {
    background-color: white;  
    border-radius: 20px;
  }
}
.bars, .day {
    width: 30px;
    height: 30px;
    color: black;
  }

  .logoAlgo {
    width: 100px;
  }
  .font_icon {
    margin-right: 10px;
    width: 20px;
    height: 20px;
  }
`;

function MyApp({ Component, pageProps }) {
  return (
    <>
      <GlobalStyle />
      <Head>
        <title>Algorismic</title>
        <link
          rel="shortcut icon"
          href="https://www.algorismic.uz/images/logo.ico"
        ></link>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="global">
        <Sidebar />
        <div className="content">
          <Headers />
          <Component {...pageProps} />
        </div>
      </div>
    </>
  );
}

export default MyApp;
